---
- name: Prueba basica Control-M con Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ejecutar prueba
      ansible.builtin.debug:
        msg: "OK - Control-M ejecuto correctamente el playbook de Ansible"
        
     - name: Mantener ejecucion durante 3 segundos
        ansible.builtin.pause:
        seconds: 3
