---
- name: Ejecutar prueba desde Control-M
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Mantener ejecucion durante 3 segundos
      ansible.builtin.pause:
        seconds: 3

    - name: Ejecutar siguiente tarea
      ansible.builtin.debug:
        msg: "OK - Control-M ejecuto correctamente el playbook de Ansible"
